sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          input_type: text
          antlers: false
          display: 'Site name'
          type: text
          icon: text
          listable: hidden
          localizable: true
      -
        handle: telephone
        field:
          input_type: text
          antlers: false
          display: Telephone
          type: text
          icon: text
          listable: hidden
          localizable: true
      -
        handle: address
        field:
          input_type: text
          antlers: false
          display: Address
          type: text
          icon: text
          listable: hidden
          localizable: true
      -
        handle: full_address
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Full address'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: email
        field:
          input_type: text
          antlers: false
          display: Email
          type: text
          icon: text
          listable: hidden
      -
        handle: facebook
        field:
          display: Facebook
          type: link
          icon: link
          listable: hidden
      -
        handle: instagram
        field:
          display: Instagram
          type: link
          icon: link
          listable: hidden
      -
        handle: tripadvisor
        field:
          display: Tripadvisor
          type: link
          icon: link
          listable: hidden
      -
        handle: site_logo
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Site logo'
          type: assets
          icon: assets
          listable: hidden
          width: 50
      -
        handle: footer_logo
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Footer logo'
          type: assets
          icon: assets
          width: 50
          listable: hidden
